metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: false

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_URL}']

name: '${HOSTNAME}'
